spring.datasource.url=jdbc:postgresql://localhost:5432/petstore_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Serve APIs under surname-specific prefix
server.servlet.context-path=/villanueva/api/v1
